I = imread('../picture/statue.png');
I = im2double(I);
sigma_s = 60;
sigma_r = 0.4;
F_nc = NC(I, sigma_s, sigma_r);
figure, imshow(I); title('Input photograph');
figure, imshow(F_nc); title('Normalized convolution');
F_eed = EE(F_nc, 0.3);
figure, imshow(F_eed); title('Edge Enhancement');
F_eec = CM(F_nc, F_eed);
figure, imshow(F_eec); title('Image Combine');